name: build-wasm
run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }}
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [main,develop]
jobs:
  build-wasm:
    uses: EddyTheCo/Common/.github/workflows/build-wasm.yml@v0.5.0
    with:
      qtModules: 'qtwebsockets qtshadertools'
      qtVersion: '6.6.0'
      emsdkVersion: '3.1.37'
      deploy_dev: ${{ (startsWith(github.base_ref, 'main'))&&(startsWith(github.head_ref, 'develop')) }}

  release-deploy:
    if: ${{ ((startsWith(github.base_ref, 'main'))&&(startsWith(github.head_ref, 'develop')))||(startsWith(github.ref, 'refs/tags/v')) }}
    needs: [build-wasm]
    uses: EddyTheCo/Common/.github/workflows/release.yml@develop
    with:
      is_app: true 
      release: ${{ startsWith(github.ref, 'refs/tags/v') }}
      release_wasm: true 
    permissions:
      contents: write
      pages: write
      id-token: write

