name: build-wasm
run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }}
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [develop]
  pull_request_target:
    types: [closed]
    branches: [main, develop]
jobs:
  build-html:
    uses: EddyTheCo/Common/.github/workflows/build-wasm.yml@develop
    permissions:
      pages: write
      id-token: write
    with:
      qtModules: 'qtwebsockets qtshadertools'
      qtVersion: '6.6.0'
      emsdkVersion: '3.1.37'
      deploy_dev:  ${{ ((github.event.pull_request.merged == true) && ((startsWith(github.base_ref, 'main'))||(startsWith(github.base_ref, 'develop'))) }
  deploy_wasm:
    needs: build-html
    if: ${{ ((github.event.pull_request.merged == true) && ((startsWith(github.base_ref, 'main'))||(startsWith(github.base_ref, 'develop'))) }

    runs-on: 'ubuntu-latest'
    permissions:
      pages: write
      id-token: write

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-html
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R

      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*/*
