name: qmllintbot
run-name: Linting QML for PR
on:

  workflow_run:
    workflows: [push-build-release]
    types:
      - completed
jobs:
  qmllint-comment:
    uses: EddyTheCo/Common/.github/workflows/qml-lint.yml@v0.5.2
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      pull-requests: write
